name = "punya"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "punya.bmkg.xyz", custom_domain = true },
  { pattern = "ava.game.naver.com.punya.bmkg.xyz", custom_domain = true },
  { pattern = "investors.spotify.com.punya.bmkg.xyz", custom_domain = true },
  { pattern = "investor.fb.com.punya.bmkg.xyz", custom_domain = true },
  { pattern = "quiz.vidio.com.punya.bmkg.xyz", custom_domain = true },
  { pattern = "ruangguru.com.punya.bmkg.xyz", custom_domain = true },


]
workers_dev = false
[vars]
UUID = "8f4e4a98-0d82-4f4a-a74d-9b547e737594"
PROXYIP = "35.219.15.90"
DNS_RESOLVER_URL = "https://dns.cloudflare.com/dns-query"
